Chore: Cleaning up files
OpenUpSA/wazimap-ng pull request #114
Opened 2020-09-19 05:45 UTC by adieyal

## Description

The repository has accumulated a number of old files which are no longer being used. In addition, some scripts are redirecting stdout and stderr streams to files rather than letting Docker handle them. Also removed out-of-date documentation from README

## Related Issue
_no issue created_

## How to test it locally
_not applicable_

## Screenshots
_not applicable_

## Changelog

### Added

### Updated
Removed capturing of stdout and stderr streams 
- scripts/django/django_q.sh
- scripts/django/web.sh
- README

Removed references to VERSION
- urls.py
- common.py

### Removed

VERSION was previously used to easily identify the git commit of a running server. It is no longer being used. The Other files related to this file:
- .githook/pre-commit
- Makefile
- urls.py
- common.py

Unused files
- Dockerfile.tmpl
- scripts/docker_build.sh
- scripts/django/startup.sh

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [ ]  🔖 issue linked
- [x]  📖 changelog filled out

### Commits

- [x]  commits are clean
- [x]  commit messages are clean

### Code Quality

- [x]  🚧 no commented out code
- [x]  🖨 no unnecessary logging
- [x]  🎱 no magic numbers

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2020-09-21 15:39 UTC, milafrerichs approved these changes

2020-09-21 15:40 UTC, milafrerichs requested changes
build fails, because you deleted docker_build script but .travis is using it.

2020-09-22 07:17 UTC, adieyal commented
Shoot - didn't realise that we were still using the build script - will restore it.

2020-09-22 07:21 UTC, milafrerichs commented
I think you can remove it form travis since it's related to a staging? 

```yaml
before_script:
- scripts/docker_build.sh staging
```

2020-09-22 09:22 UTC, milafrerichs approved these changes

2020-09-22 09:22 UTC, merged