Add more info about error logs in csv uploads
OpenUpSA/wazimap-ng pull request #123
Opened 2020-10-05 04:33 UTC by goyal1092

## Description
Added Incorrect csv log rows with error logs of csv upload.
Changed ways for logging errors in csv uploads

## Related Issue

## How to test it locally
Get a dataset file or coordinate file with errors.
After upload we should get option to download error log and incorrect csv rows in file admin.

## Changelog

* Made a common function to log upload errors
* Added incorrect csv rows log
* Changed dataloader, admin, upload task , error templates accordingly

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2020-10-07 12:51 UTC, milafrerichs requested changes
I think this should be refactored in a more general sense.

You're jumping through too many hoops and make it difficult for you and the reader of the code. 
Instead of using arrays for the errors, why not use a dict?
Adding arrays in arrays in arrays makes it really hard to understand what is going on.
If you use dictionaries it makes it much cleaner and clearer what is going on. 

```python
error = {}
...
error["Line Number"] = line_no
error["Field Name"] = "count"
error["Error Details"] = "Missing data for count"
....

errors = {}
...
errors.append({ 'line_error': error, 'values': list(row.values())})

```

pandas can write dictionaries as well. and you're transforming the arrays into separate variables by hand anyway. 

What do you think?

2020-10-07 13:09 UTC, goyal1092 commented
@milafrerichs Dicts sounds good but i am not too sure it will reduce complexity here but will surely make it a bit cleaner.
Will do that change.

On the other hand I also wanted to implement something like catching errors without going inside dataloader loop.
If we can pass vectorised df for specific cols like : 
passing : `df['count'].values` to a specific validation function which can test check for errors in list or df passed.

Like get index of all the values that are empty in the list.
It will not require a specific loop and can be done using python which will be faster than pandas iterrows and checking every value.

I am sure it will ease up the process and increase speed in process.
Only problematic area is how we remove error values from df when passing to dataloader and if we can pass dataloader with lists of data rather than generator function return

Do you think it will be a better solution and should we do something like this now or in future ?

2020-10-07 14:04 UTC, milafrerichs commented
@goyal1092 this is a very interesting and intriguing proposal. I like your way of thinking about this.

but it is not a priority for now. and your current implementation (with the changes to dict) will be good enough for now. 
But let's convert your message into an issue here in gh for future reference.

2020-10-09 10:40 UTC, goyal1092 commented
@milafrerichs Updated PR. Please review

2020-10-26 15:38 UTC, merged