Profile cache invalidation when linked geography hierarchies are updated #139
OpenUpSA/wazimap-ng pull request #144
Opened 2020-10-30 12:13 UTC by goyal1092

## Description
Invalidate cache for profile when linked geography hierarchy is updated.

## Related Issue
#139 

## How to test it locally
save geography hierarchy from admin panel and api should load hierarchy changes.
I checked if dev server logs updated.

## Changelog
* Added invalidate cache signal for geography hierarchy in cache.py
* Added test for change above

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2020-11-04 10:53 UTC, milafrerichs requested changes
can you add a signal for when the geography changes? just for completeness 
thanks.

2020-11-06 11:59 UTC, goyal1092 commented
@milafrerichs I have updated the PR.
Please review

2020-11-06 13:59 UTC, milafrerichs requested changes

2020-11-06 13:59 UTC, milafrerichs commented on tests/test_cache.py
> +            call(indicator_data.indicator.dataset.profile),tests/test_cache.py
there is something leftover. :)

2020-11-06 14:25 UTC, goyal1092 commented on tests/test_cache.py
> +            call(indicator_data.indicator.dataset.profile),tests/test_cache.py
😱 🙀

2020-11-06 14:26 UTC, goyal1092 commented on tests/test_cache.py
> +            call(indicator_data.indicator.dataset.profile),tests/test_cache.py
Fixed @milafrerichs

2020-11-09 10:15 UTC, milafrerichs requested changes

2020-11-09 10:15 UTC, milafrerichs commented on wazimap_ng/cache.py
> +    print(hierarchy_profile_ids)
leftover print statement

2020-11-09 10:37 UTC, goyal1092 commented on wazimap_ng/cache.py
> +    print(hierarchy_profile_ids)
Fixed @milafrerichs

2020-11-09 10:38 UTC, goyal1092 commented on wazimap_ng/cache.py
> +    print(hierarchy_profile_ids)
thanks

2020-11-09 10:57 UTC, milafrerichs approved these changes

2020-11-09 10:58 UTC, merged