profile indicator subcategory dropdown filtering
OpenUpSA/wazimap-ng pull request #159
Opened 2020-11-11 21:56 UTC by RomanMelnyk113

## Description
When creating a new ProfileIndicator, the subcategory dropdown does not filter options related to the selected profile - currently, subcategories from all profiles are display

## Related Issue
https://github.com/OpenUpSA/wazimap-ng/issues/157

## How to test it locally
Pre-conditions:

- different profiles available
- multiply subcategories assigned to different profiles (through categories)

To test:
1. Open "Add profile indicator" page (http://localhost:8000/admin/profile/profileindicator/add/)
2. Select different profiles from the dropdown list
3. Check available subcategories for each profile

## Changelog

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2020-11-11 23:05 UTC, RomanMelnyk113 commented on wazimap_ng/general/static/js/profile-indicator-admin.js
> +                        $.each(data, function (key, value) {
clearSubcategories(); is used twice to avoid "select" input flickering which appears during AJAX call

2020-11-11 23:06 UTC, RomanMelnyk113 commented
@milafrerichs do we need to write tests here? because I don't see any tests for the admin side

2020-11-16 10:53 UTC, milafrerichs requested changes
was meaning to submit this last week but did not complete it. sorry for the delay.

2020-11-17 22:56 UTC, RomanMelnyk113 commented on wazimap_ng/general/static/js/profile-indicator-admin.js
> +            console.log("selectedProfile", selectedProfile)
wow, sorry, missed that one...
removed.

2020-11-17 22:57 UTC, RomanMelnyk113 commented on wazimap_ng/general/static/js/profile-indicator-admin.js
> +            $subcategoryEl.append($("<option></option>").attr("value", "").text("----------"));
fixed this in a bit different way, please take a look at the latest changes.

2020-11-17 22:57 UTC, RomanMelnyk113 commented on wazimap_ng/general/static/js/profile-indicator-admin.js
> +                            $subcategoryEl.append($("<option></option>").attr("value", value.id).text(value.name));
see comment above

2021-01-29 09:34 UTC, milafrerichs approved these changes

2021-01-29 09:34 UTC, merged