Refactor serializers used for all_details, themes & pc views
OpenUpSA/wazimap-ng pull request #201
Opened 2021-01-18 09:55 UTC by goyal1092

## Description
Refactor serialisers so we can use same serializer in:
* Detail_view
* Pc view
* theme view

Add Order field in :
* Pc model
* Theme model.

Both of these fields should be orderable from admin panel using sortable2  widget.
Order should also change in api according to admin list order of data.

## Related Issue
#199 

## How to test it locally

## Changelog

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [x]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2021-03-12 10:01 UTC, goyal1092 commented
@milafrerichs Added test for this PR

2021-03-12 10:39 UTC, milafrerichs requested changes
could you clean up the tests a little bit? thanks.

2021-03-12 10:39 UTC, milafrerichs commented on tests/general/test_views.py
> +        # Reorder themes
could you rather recreate the themes here?

```python
theme1 = ThemeFactory(profile=self.profile, name="TH1", order=1)
theme2 = ThemeFactory(profile=self.profile, name="TH12, order=0)
```

2021-03-12 10:39 UTC, milafrerichs commented on tests/general/test_views.py
> +        self.pc2_th1.order = 0
same here with the sub themes?

2021-03-12 10:39 UTC, milafrerichs commented on tests/general/test_views.py
> +        # Change ordering of TH2 subthemes as well
can you split this up? into three tests?

2021-03-12 15:36 UTC, goyal1092 commented
@milafrerichs Updated PR
Please review now :)

2021-03-15 16:46 UTC, milafrerichs commented
@goyal1092 the tests fail on CI. can you fix that?

2021-03-16 16:57 UTC, goyal1092 commented
@milafrerichs Fixed
Thanks

2021-04-16 09:37 UTC, milafrerichs approved these changes

2021-04-16 09:37 UTC, merged