Fixed cache for points api endpoint
OpenUpSA/wazimap-ng pull request #240
Opened 2021-03-29 07:33 UTC by goyal1092

## Description
Fixed cache for points api endpoint

## Related Issue
#195

## How to test it locally
Visit http://localhost:8000/api/v1/profile/1/points/category/1/points/?format=json
Open location object in admin panel that exist in api endpoint above
Change data in location, save and refresh the api endpoint above and location data should change.

Delete location and refresh api endpoint.
Location should be removed from response

## Changelog
Changed cache.py to update profile categories linked to location category

### Added

### Updated

### Removed

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [x]  🔖 issue linked
- [x]  📖 changelog filled out

### Commits

- [x]  commits are clean
- [x]  commit messages are clean

### Code Quality

- [x]  🚧 no commented out code
- [x]  🖨 no unnecessary logging
- [x]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2021-05-11 08:52 UTC, milafrerichs requested changes

2021-05-11 08:52 UTC, milafrerichs commented on wazimap_ng/cache.py
> +        update_point_cache(instance)
that does not look right. a `Category` does not have a `profilecategory_set` right?

but we might want to add a cache update for the `ProfileCategory` right?

2021-05-28 06:27 UTC, milafrerichs approved these changes

2021-05-31 08:21 UTC, milafrerichs approved these changes

2021-05-31 08:21 UTC, merged

2021-06-21 17:49 UTC, goyal1092 commented
![](https://github.trello.services/images/mini-trello-icon.png) [The cache should be invalidated whenever a location is changed/deleted. Currently a hard refresh is needed. [friday to be done]](https://trello.com/c/S4jlmsrq/625-the-cache-should-be-invalidated-whenever-a-location-is-changed-deleted-currently-a-hard-refresh-is-needed-friday-to-be-done)