Issue 239 - API for profile indicators to provide last updated date
OpenUpSA/wazimap-ng pull request #242
Opened 2021-04-06 16:35 UTC by Faysalali534

## Description

## Related Issue

## How to test it locally

## Changelog

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2021-04-08 10:38 UTC, milafrerichs requested changes
the profileIndicator already has created and updated via the `BaseModel` 
there is no need to create new fields. please use the existing fields.

2021-04-09 11:52 UTC, milafrerichs requested changes
the tests are failing. please fix them.

2021-04-09 11:52 UTC, milafrerichs commented on wazimap_ng/profile/serializers/profile_indicator_serializer.py
> +      model = models.ProfileIndicator
why are you using `model.ProfileIndicator` when `ProfileIndicator` is already imported.

2021-04-09 11:52 UTC, milafrerichs commented on tests/profile/test_views.py
> +class TestProfileGeographyData:
why are those tests in your changes? they have nothing to do with your change, right?

2021-04-09 11:56 UTC, Faysalali534 commented
Yes have fixed it. Fixing conflicts.

2021-04-13 10:45 UTC, closed without merging