Fix: Changed the visible_tooltip_attribute to a list format
OpenUpSA/wazimap-ng pull request #253
Opened 2021-04-20 09:41 UTC by Geeker1

## Description
Changed the visible_ _attribute JSONField to use a list not dict

## Related Issue
#248 
## How to test it locally

## Changelog

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2021-04-20 10:32 UTC, milafrerichs requested changes
can you add the migration that is needed alongside and also create a data migration?

2021-04-20 12:24 UTC, Geeker1 commented
> can you add the migration that is needed alongside and also create a data migration?

Ok

2021-04-21 05:01 UTC, Geeker1 commented
> can you add the migration that is needed alongside and also create a data migration?

Migration script has been created, local migration to DB worked.

2021-04-21 14:22 UTC, milafrerichs commented
great, can you also create a data migration? to update all existing instances? thanks.

2021-04-22 07:48 UTC, Geeker1 commented
> great, can you also create a data migration? to update all existing instances? thanks.

Done, although I included only the values from the dict, not sure if the key is needed too.

2021-04-30 10:15 UTC, milafrerichs requested changes

2021-04-30 10:15 UTC, milafrerichs commented on wazimap_ng/points/migrate_tooltip_data.py
> +def migrate_attributes():
I meant a data **migration**

Create a new migration file and update the field there. 

it should look like this:
https://github.com/OpenUpSA/wazimap-ng/compare/chore/data-migration#diff-b5add147a76fbb22069454c268cf5e84368d0f14b12e921b3891192440ef50c6

2021-05-11 08:44 UTC, milafrerichs approved these changes

2021-05-14 18:17 UTC, merged