Fixed issue in failing highlights serializer
OpenUpSA/wazimap-ng pull request #301
Opened 2021-06-08 06:16 UTC by goyal1092

## Description
Fixed issue for highlight serializer

## Related Issue
https://trello.com/c/uzo0fj1N/783-profile-highlights-if-there-is-no-data-for-the-profile-highlight-for-a-geography-the-app-might-fail

## How to test it locally

## Changelog

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2021-06-08 07:07 UTC, milafrerichs commented
@goyal1092 can you look at this and see if there is anything we can reuse. since it's almost the same thing I bet we can and should reuse as much as possible. 
also look at @adieyal change here: https://github.com/OpenUpSA/wazimap-ng/pull/298

2021-06-08 07:15 UTC, goyal1092 commented
@milafrerichs By this do you mean this Pr: https://github.com/OpenUpSA/wazimap-ng/pull/293 ?

2021-06-08 07:18 UTC, milafrerichs commented
> @milafrerichs By this do you mean this Pr: #293 ?

yes, sorry forgot to link the PR :(

2021-06-08 07:39 UTC, goyal1092 commented
@milafrerichs We can not use anything from this PR as key metrics query metrics and we will have to query highlights
If you want I can format my PR according to PR: #293

2021-07-29 06:54 UTC, goyal1092 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Metros return a 500 on GIZ profile](https://trello.com/c/jOMxsedD/863-metros-return-a-500-on-giz-profile)

2021-08-05 12:48 UTC, adieyal requested changes
Code looks good and fixes the bug. Please add a unit test

2021-08-23 09:57 UTC, merged