Check for dataset profile perms before deleting datasets from admin list view
OpenUpSA/wazimap-ng pull request #330
Opened 2021-08-02 06:49 UTC by goyal1092

## Description
Check for dataset permissions before deleting data from list view of dataset admin

## Related Issue
https://trello.com/c/nh1PM1ro/869-dataadmin-is-able-to-delete-dataset-without-perms-from-list-view-of-admin-panel

## How to test it locally

## Changelog

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2021-08-05 10:44 UTC, adieyal commented on wazimap_ng/datasets/admin/base_admin_model.py
> +            if queryset.exclude(profile__in=user_profiles).count() == 0:
please change this to something like:

```
selected_objects_without_permission = queryset.exclude(profile__in=user_profiles).count() > 0
if selected_objects_without_permission:
    ...
else:
   ...
```
Makes the code more self-documenting

2021-08-05 11:19 UTC, adieyal requested changes
Please add a unit test

2021-08-16 09:26 UTC, goyal1092 commented
@adieyal Ready for review

2021-09-02 09:14 UTC, goyal1092 commented
closing this PR as We will not allow user to delete dataset

2021-09-02 09:14 UTC, closed without merging